# Generated by Django 5.2.5 on 2025-08-30 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trip_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=200)),
                ('current_latitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('current_longitude', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TripInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.BigIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_station', models.CharField(max_length=200)),
                ('end_station', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CrowdSourcedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200)),
                ('transport_officer', models.BooleanField(default=False)),
                ('is_delay', models.BooleanField(default=False)),
                ('cleanliness', models.IntegerField(default=5)),
                ('crowdedness', models.IntegerField(default=5)),
                ('carriage_number', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowdsourced_data', to='api.tripinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0.0)),
                ('carbon_emissions_saved_kg', models.FloatField(default=0.0)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tripinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_latitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('start_longitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('end_latitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('end_longitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.BigIntegerField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=4)),
                ('trip_leg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tripleg')),
            ],
        ),
    ]
