# Generated by Django 5.2.5 on 2025-08-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripleg',
            name='path',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='train',
            name='current_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='train',
            name='current_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='end_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='end_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='start_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='start_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
