# Generated by Django 5.2.5 on 2025-08-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='next_stop',
            field=models.CharField(default=228920, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripleg',
            name='end_station',
            field=models.CharField(default=228920, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripleg',
            name='last_stretch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='start_station',
            field=models.CharField(default=228920, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripleg',
            name='trip_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.tripinfo'),
            preserve_default=False,
        ),
    ]
