import { StyleSheet } from "react-native";
import { Theme } from "../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  innerContainer: {
    flex: 1,
    justifyContent: "space-between",
  },
  map: {
    width: "100%",
    height: "100%",
  },
  searchContainer: {
    position: "absolute",
    width: "100%",
    zIndex: 100,
  },
  resultsWrapper: {
    marginTop: 16,
    backgroundColor: Theme.COLORS.WHITE,
    borderRadius: 8,
    maxHeight: 800,
  },
  searchFrom: {
    zIndex: 10,
    position: "absolute",
    backgroundColor: Theme.COLORS.WHITE,
    padding: 16,
    width: "100%",
  },
  searchTo: {
    zIndex: 50,
    position: "absolute",
    top: 40,
    backgroundColor: Theme.COLORS.WHITE,
    padding: 12,
    width: "100%",
  },
  locationsContainer: {
    zIndex: 50,
    width: "100%",
    padding: 12,
    top: 30,
    backgroundColor: Theme.COLORS.WHITE,
  },
  resultItem: {
    width: "100%",
    height: 40,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  selectedView: {
    top: 60,
    position: "absolute",
    right: 10,
    backgroundColor: Theme.COLORS.WHITE,
    zIndex: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 100,
    shadowColor: Theme.COLORS.BLACK,
    shadowOpacity: 0.5,
    shadowRadius: 5,
    shadowOffset: {
      height: 2,
      width: 0,
    },
  },
  returnToLocation: {
    top: 130,
    position: "absolute",
    right: 10,
    backgroundColor: Theme.COLORS.WHITE,
    zIndex: 10,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 100,
    shadowColor: Theme.COLORS.BLACK,
    shadowOpacity: 0.5,
    shadowRadius: 5,
    shadowOffset: {
      height: 2,
      width: 0,
    },
  },
  trainIcons: {
    alignItems: "center",
    display: "flex",
    flexDirection: "row",
    gap: 2,
  },
  cardContainer: {
    backgroundColor: Theme.COLORS.WHITE,
    borderLeftColor: Theme.COLORS.PRIMARY,
    borderLeftWidth: 10,
    borderRadius: 10,
    padding: 20,
    gap: 12,
    marginVertical: 4,
    shadowColor: Theme.COLORS.BLACK,
    shadowOpacity: 0.08,
    shadowOffset: {
      width: 0,
      height: 10,
    },
  },
  cardSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  cardSectionSpaced: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    justifyContent: "space-between",
  },
  cardTitle: {
    fontFamily: Theme.FONT.MEDIUM,
  },
  resultsOverlay: {
    height: 450,
    width: "100%",
    zIndex: 50,
    backgroundColor: Theme.COLORS.WHITE,
    bottom: 60,
    position: "absolute",
    borderTopColor: Theme.COLORS.PRIMARY,
    borderWidth: 1,
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    padding: 20,
    display: "flex",
    gap: 10,
  },
  resultsOverlayWithBigIndex: {
    zIndex: 80,
  },
  resultsContainer: {
    display: "flex",
  },
  resultsText: {
    fontSize: 20,
    fontFamily: Theme.FONT.MEDIUM,
  },
  resultsHeader: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  stationNamesContainer: {
    display: "flex",
    gap: 20,
  },
  cardInner: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    right: 5,
  },
  cardInnerTitle: {
    fontFamily: Theme.FONT.MEDIUM,
  },
});
